neet_cols = [
    "neet_year_minus_1",
    "neet_year_minus_2",
    "neet_year_minus_3",
    "neet_year_minus_4",
    "neet_year_minus_5",
    "neet_year_minus_6",
    "neet_year_minus_7",
]
ps_cols = [
    "ps_mean_Samfundsfag",
    "ps_mean_Engelsk",
    "ps_mean_Idræt",
    "ps_mean_Fysik/kemi",
    "ps_mean_Matematik",
    "ps_mean_Kristendomskundskab",
    "ps_mean_Historie",
    "ps_mean_Obligatorisk selvvalgt opgave",
    "ps_mean_Tysk",
    "ps_mean_Geografi",
    "ps_mean_Biologi",
    "ps_mean_Fællesprøve i fysik/kemi, biologi og geografi",
    "ps_mean_Dansk",
    "ps_mean_Tysk 2. fremmedsprog",
    "ps_mean_Obligatorisk projektopgave",
    "ps_mean_Fransk",
    "ps_mean_Fransk 2. fremmedsprog",
    "ps_mean_Biologi/fysik/kemi",
    "ps_mean_Håndarbejde",
    "ps_mean_OBL",
    "ps_mean_Fransk 3. fremmedsprog",
    "ps_mean_Musik",
    "ps_mean_Frivillig selvvalgt opgave",
    "ps_mean_Madkundskab",
    "ps_mean_Sløjd",
    "ps_mean_Billedkunst",
    "ps_mean_Håndværk og design",
    "ps_mean_Tysk 3. fremmedsprog",
    "ps_mean_Fri selvvalgt opgave",
    "ps_mean_Fællesprøve i samfundsfag og historie",
    "ps_mean_Fællesprøve i samfundsfag, historie",
    "ps_mean_Spansk",
    "ps_mean_Naturfag",
    "ps_mean_Frivillig projektopgave (naturfag)",
    "ps_mean_Sundhed og sociale forhold",
    "ps_mean_Latin",
    "ps_mean_Medier",
    "ps_mean_Metal og motorværksted",
    "ps_mean_Iværksætter",
]
hs_cols = [
    "hs_mean_Spansk begyndersprog",
    "hs_mean_Engelsk",
    "hs_mean_Tysk",
    "hs_mean_Samfundsfag",
    "hs_mean_Oldtidskundskab",
    "hs_mean_Musik",
    "hs_mean_Geografi",
    "hs_mean_Naturfag",
    "hs_mean_Religion",
    "hs_mean_Biologi",
    "hs_mean_Dansk",
    "hs_mean_Kemi",
    "hs_mean_Billedkunst",
    "hs_mean_Informationsteknologi",
    "hs_mean_Erhvervsjura",
    "hs_mean_Afsætning",
    "hs_mean_Matematik",
    "hs_mean_Erhvervsøkonomi",
    "hs_mean_Fransk",
    "hs_mean_EU og internationalt økonomisk samarbejde",
    "hs_mean_Fysik",
    "hs_mean_Mediefag",
    "hs_mean_Idræt",
    "hs_mean_Naturvidenskabelig faggruppe",
    "hs_mean_Naturgeografi",
    "hs_mean_Eksamensprojekt",
    "hs_mean_International økonomi",
    "hs_mean_Erhvervscase",
    "hs_mean_Dramatik",
    "hs_mean_Historie",
    "hs_mean_Psykologi",
    "hs_mean_Finansiering",
    "hs_mean_Filosofi",
    "hs_mean_Design",
    "hs_mean_Idehistorie",
    "hs_mean_Kulturforståelse",
    "hs_mean_Samtidshistorie",
    "hs_mean_Latin begyndersprog",
    "hs_mean_Teknologi",
    "hs_mean_Teknikfag",
    "hs_mean_Større skriftlig opgave",
    "hs_mean_Virksomhedsinformation",
    "hs_mean_Kultur- og samfundsfaggruppe",
    "hs_mean_Innovation",
    "hs_mean_Virksomhedsøkonomi",
    "hs_mean_Teknologihistorie",
    "hs_mean_Italiensk begyndersprog",
    "hs_mean_Studieområde - erhvervscase",
    "hs_mean_Fysik-kemi",
    "hs_mean_Programmering",
    "hs_mean_Datalogi",
    "hs_mean_Astronomi",
    "hs_mean_International teknologi og kultur",
    "hs_mean_Russisk begyndersprog",
    "hs_mean_Statik og styrkelære",
    "hs_mean_Kommunikation/it",
    "hs_mean_Markedskommunikation",
    "hs_mean_Retorik",
    "hs_mean_Andet",
    "hs_mean_Dans",
    "hs_mean_Astrofysik",
    "hs_mean_Multimedier",
    "hs_mean_Studieområde - det internationale område",
    "hs_mean_Erhvervspsykologi",
    "hs_mean_Tyrkisk begyndersprog",
    "hs_mean_Projektfag",
    "hs_mean_Statistik",
    "hs_mean_Organisation",
    "hs_mean_Studieområdet del 2",
    "hs_mean_It",
    "hs_mean_International (USA)",
    "hs_mean_Almen studieforberedelse",
    "hs_mean_Tysk fortsættersprog",
    "hs_mean_Nationaløkonomi",
    "hs_mean_Fransk begyndersprog",
    "hs_mean_Japansk begyndersprog",
    "hs_mean_Græsk begyndersprog",
    "hs_mean_Teater",
    "hs_mean_Fransk fortsættersprog",
    "hs_mean_Arabisk begyndersprog",
    "hs_mean_Materialeteknologi",
    "hs_mean_Kultur/historie",
    "hs_mean_Studieretningsprojekt",
    "hs_mean_Almen sprogforståelse",
    "hs_mean_Kvalitetsstyring",
    "hs_mean_Marketing",
    "hs_mean_Filosofi og teknologi",
    "hs_mean_Science",
    "hs_mean_Naturvidenskabeligt grundforløb",
    "hs_mean_Tysk begyndersprog",
    "hs_mean_Dansk som andetsprog",
    "hs_mean_Design og arkitektur",
    "hs_mean_Informatik",
    "hs_mean_Dansk IT",
    "hs_mean_Engelsk IT",
    "hs_mean_Kinesisk begyndersprog",
    "hs_mean_Projektopgave",
    "hs_mean_Studieområde",
    "hs_mean_Teknikfag - proces levnedsmiddel og sundhed",
    "hs_mean_Teknikfag - design og produktion",
    "hs_mean_Teknikfag - byggeri og energi",
    "hs_mean_Kinesisk områdestudium",
    "hs_mean_Bioteknologi",
    "hs_mean_Økonomisk grundforløb",
    "hs_mean_Naturvidenskabelig faggruppe - Biologi",
    "hs_mean_Musik og lydproduktion",
    "hs_mean_Byggeteknologi",
    "hs_mean_Kinesisk fortsættersprog",
    "hs_mean_Studieretningsopgave",
    "hs_mean_Industriteknologi",
    "hs_mean_Spansk fortsættersprog",
    "hs_mean_Kultur- og samfundsfaggruppe - Religion",
    "hs_mean_Naturvidenskabelig faggruppe - Kemi",
    "hs_mean_Naturvidenskabelig faggruppe - Geografi",
    "hs_mean_Geovidenskab",
    "hs_mean_Portugisisk begyndersprog",
    "hs_mean_Teknikfag - udvikling og produktion",
    "hs_mean_Kultur- og samfundsfaggruppe - Samfundsfag",
    "hs_mean_Kultur- og samfundsfaggruppe - Historie",
    "hs_mean_FyMa",
    "hs_mean_Studieområde del 1",
    "hs_mean_Fødevareteknologi",
    "hs_mean_Produktudvikling",
    "hs_mean_Teknikfag - digitalt design og udvikling",
    "hs_mean_Studieområdeprojekt",
    "hs_mean_Erhvervsområdeprojekt",
    "hs_mean_Erhvervsinformatik",
    "hs_mean_Teknikfag byggeri og energi, el",
]
NUMERICAL_COLS = (
    neet_cols
    + ps_cols
    + hs_cols
    + [
        "he_mean_grade",
        "bredt_loen_beloeb_mean",
        "tilstand_laengde_mdr_mean",
        "gpa",
        "age",
        "currently_revoked_license",
        "has_had_revoked_licenses",
        "curr_susp_sent",
        "has_had_susp_sent",
        "perpetual_susp_sent",
        "boedeblb_mean",
        "dagboant_mean",
        "dagbobel_mean",
    ]
)

ONEHOT_COLS = [
    "sex",
    "immigrant_type",
    'origin_country',
    'native',
    'international',
    "hs_mode_instnr",
    "hs_mode_udd",
    "he_mode_instnr",
    "he_mode_udd",
    "bopael_kom_kode_mode",
    "atp_bidrag_sats_kode_mode",
    "soc_status_kode_mode",
    "arb_hoved_bra_db07_mode",
    "disco_kode_mode",
    "arb_sektorkode_mode",
    "audd",
    "instnr",
    "disced",
    "field",
    'in_jail',
    'has_been_in_jail',
]
COUNT_COLS = [
    "aktionsdiagnose",
    "urgency",
    "patienttype",
    "atc",
    "ger7_no_conviction",
    "ger7_conviction",
    "ger7_conf_no_convs",
    "ger7_conf_convs",
    "ger7_charges",
    "ger7_victims",
    "ger7_minor_charge",
]
